services:
  - type: web
    name: smart-reply
    env: java
    plan: free
    region: frankfurt
    buildCommand: "./mvnw clean package -DskipTests"
    startCommand: "java -jar target/*.jar"
    envVars:
      - key: JAVA_VERSION
        value: 17
      - key: GEMINI_URL
      - key: GEMINI_API_KEY
